version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "rust"
      - "skip changelog"
    groups:
      rust-dependencies:
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "github actions"
      - "skip changelog"
    groups:
      github-actions:
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "python"
    groups:
      # We don't limit grouping for Python to just minor/patch versions, since pip doesn't follow
      # semver, plus having to update CHANGELOG.md means it's easier to just have a single PR.
      python-dependencies:
        patterns:
          - "*"
