version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "rust"
      - "skip changelog"
    groups:
      rust-dependencies:
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "github actions"
      - "skip changelog"
    groups:
      github-actions:
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      # We set this to a more frequent interval than the above since uv is still under rapid
      # iteration, and we'll generally want to be on a recent (if not the latest) version.
      interval: "weekly"
    labels:
      - "dependencies"
      - "python"
