name: Release Buildpack

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: Execute the release workflow but skip any steps that publish (for testing purposes)
        type: boolean
        default: false

jobs:
  release:
    name: Release
    uses: heroku/languages-github-actions/.github/workflows/_buildpacks-release.yml@latest
    with:
      app_id: ${{ vars.LINGUIST_GH_APP_ID }}
      dry_run: ${{ inputs.dry_run }}
    secrets:
      app_private_key: ${{ secrets.LINGUIST_GH_PRIVATE_KEY }}
      cnb_registry_token: ${{ secrets.CNB_REGISTRY_RELEASE_BOT_GITHUB_TOKEN }}
      docker_hub_user: ${{ secrets.DOCKER_HUB_USER }}
      docker_hub_token: ${{ secrets.DOCKER_HUB_TOKEN }}
